config/routes.rb
Rails.application.routes.draw do
  resources :newsletter_users, only: [:new, :create]
  resources :messages, only: [:new, :create]
  resources :posts, only: [:new, :create, :update, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/front', to: "posts#front", via: :get
  match '/astrology', to: "posts#astrology", via: :get
  match '/meditation', to: "posts#meditation", via: :get
  match '/yoga', to: "posts#yoga", via: :get
  match '/life', to: "posts#life", via: :get

  root 'posts#front'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/newsletter_user.rb
class NewsletterUser < ApplicationRecord

	validates :email, :email_format => { :message => 'Email is not valid' }

end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:subject, :question, :type)
    end
end

app/controllers/newsletter_users_controller.rb
class NewsletterUsersController < ApplicationController
  before_action :set_newsletter_user, only: [:show, :edit, :update, :destroy]

  # GET /newsletter_users
  # GET /newsletter_users.json
  def index
    @newsletter_users = NewsletterUser.all
  end

  # GET /newsletter_users/1
  # GET /newsletter_users/1.json
  def show
  end

  # GET /newsletter_users/new
  def new
    @newsletter_user = NewsletterUser.new
  end

  # GET /newsletter_users/1/edit
  def edit
  end

  # POST /newsletter_users
  # POST /newsletter_users.json
  def create
    @newsletter_user = NewsletterUser.new(newsletter_user_params)

    respond_to do |format|
      if @newsletter_user.save
        format.html { redirect_to front_path, notice: ' Your Email was successfully registered ' }
        format.json { render :show, status: :created, location: front_path }
      else
        format.html { redirect_to front_path, notice: 'Your Email was not successfully registered' }
        format.json { render json: @newsletter_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletter_users/1
  # PATCH/PUT /newsletter_users/1.json
  def update
    respond_to do |format|
      if @newsletter_user.update(newsletter_user_params)
        format.html { redirect_to @newsletter_user, notice: 'Newsletter user was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsletter_user }
      else
        format.html { render :edit }
        format.json { render json: @newsletter_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletter_users/1
  # DELETE /newsletter_users/1.json
  def destroy
    @newsletter_user.destroy
    respond_to do |format|
      format.html { redirect_to newsletter_users_url, notice: 'Newsletter user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter_user
      @newsletter_user = NewsletterUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_user_params
      params.require(:newsletter_user).permit(:email)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def front
    
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    
  end

  def astrology
    @posts = Post.where(:posttype => 0)
  end

  def meditation
    @posts = Post.where(:posttype => 1)
  end

  def yoga
    @posts = Post.where(:posttype => 2)
  end

  def life
    @posts = Post.where(:posttype => 3)
  end


  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :resource, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/newsletter_users_helper.rb
module NewsletterUsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"  lazyload>

<% cache do %>
<div class="container" id = "custom">    	
  <div class="row">
    <div class="col-lg-12 col-sm-12">

      <div class="col-md-3 col-sm-12">
        <ul class="list-unstyled" style = "text-align:center;">
          <li><%= link_to "Santoshaham", "http://www.tdcdigitalmedia.com" %><li>
          <li><%= link_to "About Me", root_path %></li>          
          <li><%= link_to "Terms", root_path %></li>                  
          <li><%= link_to "Policy", root_path %></li>
          <li><%= link_to "Contact Me", root_path %></li>
        </ul>
      </div>


      <div class="col-md-6 col-sm-12">
        <ul class="list-unstyled" style = "text-align:center;">
          <li><p>SIGN UP FOR NEWSLETTER</p><li>          
          <li><p><%= render 'newsletter_users/form' %></p><li>   
        </ul>
      </div>


       <div class="col-md-3 col-sm-12">
       <div class="table">
         <ul class="social" style= "list-style-type: none; text-align: center; ">
           <li> <a href="//www.youtube.com/channel/UCKlwcipJl3z_CD_8xmIt7Vg"> <i class=" fa fa-youtube"></i> </a> </li>           
            <li> <a href="//www.instagram.com/santoshaham/"> <i class="fa fa-instagram"></i> </a> </li> 
            <li> <a href="//twitter.com/OaSaurav"> <i class="fa fa-twitter"></i> </a> </li>
            <li> <a href="#"> <i class="fa fa-tumblr"></i> </a> </li>                  
        </ul>
        </div>

      </div>       

      
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-12" style="color: #fff">
        <p class="muted pull-right" style = "font-size: 10px; text-align: center;">© <%= Time.now.year %> SANTOSHAHAM. All Rights Reserved</p>
      </div>
    </div>
  </div>
</div>

<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" style="background: black;">
        <span class="icon-bar" ></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>

      <ul class="nav navbar-nav navbar-left">
        <li>
          <%= image_tag("//s3-us-west-2.amazonaws.com/wacbacassetsdonttouch/wacbacassets/jgdfreebg.png", :alt => "Santosham", :size => "50x50") %>          
        </li>
      </ul>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">      
         <ul class="nav navbar-nav navbar-right">        
        <li>
          <%= link_to "HOME", root_path %>
        </li>        
        <li>
          <%= link_to "ASTROLOGY", astrology_path %>
        </li>         
        <li>
          <%= link_to "MEDITATION", meditation_path %>
        </li>
        <li>
          <%= link_to "YOGA", yoga_path %>
        </li> 
        <li>
          <%= link_to 'LIFE', life_path %>
        </li>
        <li>
          <%= link_to "YOUR QUESTIONS", root_path %>
        </li>                                                         
      </ul>      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Santoshaham</title>

    <%= favicon_link_tag '//s3-us-west-2.amazonaws.com/wacbacassetsdonttouch/wacbacassets/jgdfreebg.png' %>

    <script src="https://snapwidget.com/js/snapwidget.js"></script>
    

    <link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet"  lazyload>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"  lazyload>

    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js" >
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" async></script>
      
  
<!-- font -->

   <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Great+Vibes|Baloo+Chettan|Damion|Heebo|Kaushan+Script|Lobster|Playfair+Display+SC" rel="stylesheet"  lazyload>
    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/card/1.3.1/js/card.min.js" lazyload>
      
    <meta name="description" content="Sprituality, Meditation, Yoga and Astrology. I have worked with Maharshi Mahesh Yogi for 18 years, travelled the world, changed the lives of thousands through my knowledge in India, and now its time to give to the world!">  

  
      
    <!-- <meta name="viewport" content="width=device-width"> -->
    <meta content="Santoshaham" property="og:title" />   


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>   
  
  <div class = "col-lg-12 col-sm-12 col-xs-12">
    <div class = "container">
          <%= content_tag :div, alert, class: "flash bg-danger" if alert %>
          <%= content_tag :div, notice, class: "flash bg-success" if notice %>

    </div>
  </div>



    <%= render 'layouts/navbar' %>  


    <%= yield %>
    

    <%= render 'layouts/footer' %> 

    
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :message_subject %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, id: :message_question %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.number_field :type, id: :message_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Question</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.subject %></td>
        <td><%= message.question %></td>
        <td><%= message.type %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Question:</strong>
  <%= @message.question %>
</p>

<p>
  <strong>Type:</strong>
  <%= @message.type %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/newsletter_users/_form.html.erb
<%= form_for [ NewsletterUser.new ] do |form| %> 

  <div class="field">
    <%= form.label :email, :style => "color: yellow;" %>
    <%= form.text_field :email, :style => "color: black;" %>
  

    <%= form.submit 'Sign Up', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/newsletter_users/edit.html.erb
<!-- <h1>Editing Newsletter User</h1>

<%= render 'form', newsletter_user: @newsletter_user %>

<%= link_to 'Show', @newsletter_user %> |
<%= link_to 'Back', newsletter_users_path %>
 -->

app/views/newsletter_users/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Newsletter Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsletter_users.each do |newsletter_user| %>
      <tr>
        <td><%= newsletter_user.email %></td>
        <td><%= link_to 'Show', newsletter_user %></td>
        <td><%= link_to 'Edit', edit_newsletter_user_path(newsletter_user) %></td>
        <td><%= link_to 'Destroy', newsletter_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsletter User', new_newsletter_user_path %>
 -->

app/views/newsletter_users/new.html.erb
<!-- <h1>New Newsletter User</h1>

<%= render 'form', newsletter_user: @newsletter_user %>

<%= link_to 'Back', newsletter_users_path %>
 -->

app/views/newsletter_users/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @newsletter_user.email %>
</p>

<%= link_to 'Edit', edit_newsletter_user_path(@newsletter_user) %> |
<%= link_to 'Back', newsletter_users_path %>
 -->

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :resource %>
    <%= form.text_field :resource, id: :post_resource %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.number_field :type, id: :post_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_header.html.erb
<div class="headerdiv" id = "herodiv">

	<div class = "col-lg-12 col-sm-12 col-xs-12" id = "leftheaderdiv">

		<h1 style = "color: black;">SANTOSHAHAM</h1>

		<p style = "margin-top: 2%;  color: black; padding-right: 40px; padding-left: 40px; text-align: justify;"><strong><i>
		I started my spiritual journey around 30 years ago. Worked very closely on the TM Movement for around 18 years. Learned, experienced, researched and practiced different forms of meditation, yoga, astrology and ayurveda. Through the years, I researched and developed more focused and customized ways of tackling spiritual problems. I have used my knowledge to help people in India solve their problems by providing spiritual consultancy for more than 17 years. Now, I am embarking on another journey to reach out and help the people around the World find peace, tranquility, bliss and their purpose in life. 
		</i></strong></p>		

		<h4 style = "color: black; margin-top: 1%; padding-right: 20px; padding-left: 20px;">Ask or Share with me your spritual questions and problems, I will be happy to help you solve them! </h4>
		<h3 style = "color: black; margin-top: 1%; padding-right: 20px; padding-left: 20px; ">Jai Guru Dev</h3>
	</div>

</div>

app/views/posts/_instagram.html.erb

	<div class="headerdiv" style = "background: #FFF;">

		<div class = "col-lg-12 col-sm-12 col-xs-12" id = "leftheaderdiv" >
			<h1 style = "margin-top: 1%; color: black;">INSTAGRAM</h1>		
		</div>

		<!-- SnapWidget -->
	
		<iframe src="https://snapwidget.com/embed/400680" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%; "></iframe>

	</div>

app/views/posts/_postsharedresource.html.erb
<%= @posts.each do |post|%>

	<div class = "col-lg-12 col-sm-12 col-xs-12" >
		<div class = "w3-panel w3-card-2">
			<div class = "w3-panel w3-card-2">
					<h1>
					  <strong>Title:</strong>
					  <%= post.title %>
					</h1>

					<p>		  
					  <%= post.resource %>
					</p>
					
			</div>
		</div>

	<%= link_to 'Edit', edit_post_path(post) %>
	</div>

<% end %>





app/views/posts/_videos.html.erb

	<div class="headerdiv"  style = "background: #FFF;">

		<div class = "col-lg-12 col-sm-12 col-xs-12" id = "leftheaderdiv" >
			<h1 style = "margin-top: 1%;  color: black;">VIDEOS</h1>		
			<h5 style = "margin-top: 10%; color: black;">UPCOMING</h5>
		</div>


<!-- <iframe src="http://www.youtube.com/embed/?listType=user_uploads&list=akhouri santosh" width="480" height="400"></iframe> -->
	</div>

                   

app/views/posts/astrology.html.erb
<div class="headerdiv" style = "background: #FFF; margin-top: 10%;">
	<div class = "col-lg-12 col-sm-12 col-xs-12" id = "leftheaderdiv" >
		<h1 style = "margin-top: 1%; color: black;">ASTROLOGY</h1>	
		<%= render "posts/postsharedresource" %>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/front.html.erb

<div class = "col-sm-12">
	<%= render "header" %>
	<%= render "videos" %>
	<%= render "instagram" %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Resource</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.resource %></td>
        <td><%= post.type %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/life.html.erb
<div class="headerdiv" style = "background: #FFF; margin-top: 10%;">
	<div class = "col-lg-12 col-sm-12 col-xs-12" id = "leftheaderdiv" >
			<h1 style = "margin-top: 1%; color: black;">LIFE</h1>	
			<%= render "posts/postsharedresource" %>
	</div>
</div>

app/views/posts/meditation.html.erb
<div class="headerdiv" style = "background: #FFF; margin-top: 10%;">
	<div class = "col-lg-12 col-sm-12 col-xs-12" id = "leftheaderdiv" >
		<h1 style = "margin-top: 1%; color: black;">MEDITATION</h1>	
		<%= render "posts/postsharedresource" %>
	</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @post.resource %>
</p>

<p>
  <strong>Type:</strong>
  <%= @post.type %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/yoga.html.erb
<div class="headerdiv" style = "background: #FFF; margin-top: 10%;">
	<div class = "col-lg-12 col-sm-12 col-xs-12" id = "leftheaderdiv" >
		<h1 style = "margin-top: 1%; color: black;">YOGA</h1>	
		<%= render "posts/postsharedresource" %>	
	</div>
</div>
